
package ec.fraud.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FraudService", targetNamespace = "http://ws.fraud.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FraudService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ec.fraud.soapclient.PredictResponse2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "predict", targetNamespace = "http://ws.fraud.ec/", className = "ec.fraud.soapclient.Predict")
    @ResponseWrapper(localName = "predictResponse", targetNamespace = "http://ws.fraud.ec/", className = "ec.fraud.soapclient.PredictResponse")
    public PredictResponse2 predict(
        @WebParam(name = "arg0", targetNamespace = "")
        PredictRequest arg0);

}
