
package ec.fraud.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FraudService", targetNamespace = "http://ws.fraud.ec/", wsdlLocation = "http://localhost:8080/fraud-soap/FraudService?wsdl")
public class FraudService_Service
    extends Service
{

    private final static URL FRAUDSERVICE_WSDL_LOCATION;
    private final static WebServiceException FRAUDSERVICE_EXCEPTION;
    private final static QName FRAUDSERVICE_QNAME = new QName("http://ws.fraud.ec/", "FraudService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/fraud-soap/FraudService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRAUDSERVICE_WSDL_LOCATION = url;
        FRAUDSERVICE_EXCEPTION = e;
    }

    public FraudService_Service() {
        super(__getWsdlLocation(), FRAUDSERVICE_QNAME);
    }

    public FraudService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRAUDSERVICE_QNAME, features);
    }

    public FraudService_Service(URL wsdlLocation) {
        super(wsdlLocation, FRAUDSERVICE_QNAME);
    }

    public FraudService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRAUDSERVICE_QNAME, features);
    }

    public FraudService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FraudService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FraudService
     */
    @WebEndpoint(name = "FraudServicePort")
    public FraudService getFraudServicePort() {
        return super.getPort(new QName("http://ws.fraud.ec/", "FraudServicePort"), FraudService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FraudService
     */
    @WebEndpoint(name = "FraudServicePort")
    public FraudService getFraudServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fraud.ec/", "FraudServicePort"), FraudService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRAUDSERVICE_EXCEPTION!= null) {
            throw FRAUDSERVICE_EXCEPTION;
        }
        return FRAUDSERVICE_WSDL_LOCATION;
    }

}
